package com.example.android.dagger.event

object ActivityEvent {
    const val FETCH_DATA_FROM_DB = "FETCH_DATA_FROM_DB"
    const val SAVE_DATA_TO_DB = "SAVE_DATA_TO_DB"
    const val OPEN_DETAIL_PAGE = "OPEN_DETAIL_PAGE"
    const val OPEN_SEARCH_FRAGMENT = "OPEN_SEARCH_FRAGMENT"
    const val OPEN_SHARE_LINK_FLOW = "OPEN_SHARE_LINK_FLOW"
    const val CLOSE_BOTTOM_SHEET_DIALOG = "CLOSE_BOTTOM_SHEET_DIALOG"
    const val BOOKMARK_ICON_CLICKED = "BOOKMARK_ICON_CLICKED"
    const val CLOSE_DETAIL_ACTIVITY = "CLOSE_DETAIL_ACTIVITY"
    const val OPEN_BOOKMARK_FRAGMENT = "OPEN_BOOKMARK_FRAGMENT"
    const val CLOSE_BOOK_MARK_FRAGMENT = "CLOSE_BOOK_MARK_FRAGMENT"
}